import { Injectable } from '@angular/core';
import { NotificIationnterface } from 'src/app/interface/notification.interface';
import { SupplierInterface } from 'src/app/interface/supplier.interface';
@Injectable({
  providedIn: 'root'
})
export class DatamockService {

  notificationList: NotificIationnterface[] = [
    {
      _id: 1,
      name: 'Abraham linkon',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'diary',
      function: 'client',
      startIn: '2014-02-09',
      status: 'Ativo'
    },
    {
      _id: 2,
      name: 'Brad Pit',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'diary',
      function: 'client',
      startIn: '2014-02-09',
      status: 'Ativo'
    },
    {
      _id: 3,
      name: 'Katy Pary',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'diary',
      function: 'client',
      startIn: '2014-02-09',
      status: 'Inativo'
    },
    {
      _id: 4,
      name: 'Vin Disel',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'diary',
      function: 'client',
      startIn: '2014-02-09',
      status: 'Inativo'
    },
    {
      _id: 5,
      name: 'Drake',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Inativo'
    },
    {
      _id: 6,
      name: 'Travis Scots',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Inativo'
    },
    {
      _id: 7,
      name: 'Avril Lavine',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Ativo'
    },
    {
      _id: 8,
      name: 'Ana maria braga',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Ativo'
    },
    {
      _id: 9,
      name: 'Faustão',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Ativo'
    },
    {
      _id: 10,
      name: 'Al abduh jaba mohamed mia khalifa',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Ativo'
    },
    {
      _id: 11,
      name: 'Bolsonaro',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Ativo'
    },
    {
      _id: 12,
      name: 'Putin',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Ativo'
    },
    {
      _id: 13,
      name: 'Donald trump',
      content: 't is a long established fact that a reader will be distracted by the readable',
      time: '13:23:02',
      filter: '..',
      repetition: 'week',
      function: 'supplier',
      startIn: '2014-02-09',
      status: 'Ativo'
    },

  ];




  supplier: SupplierInterface[] = [
    {
      _id: 1,
      name: 'Abraham linkon Abraham linkon Abraham linkonAbraham linkonAbraham linkonAbraham linkonAbraham linkon',
      email: 'exemplo@xequematervqwetbbqgbeedewfrebrbqeebrtbwrtre.com',
      cnpj: '42788247000164',
      permition: 'Permição BBBBBBBBBBBB',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: true,
      material: 'plasticococococo',
      price: '149934937',
      tel: '6140028922',
      type: 'Fornecedor',
      funcoes: 'administrador',
      status: 'Ativo'
    },
    {
      _id: 2,
      name: 'Brad Pit',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição BBBBBBBBBBBB',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: true,
      material: 'plasticococococo',
      price: '149934937',
      tel: '6140028922',
      type: 'Fornecedor',
      funcoes: 'kyc',
      status: 'Ativo'
    },
    {
      _id: 3,
      name: 'Katy Pary',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição BBBBBBBBBBBB',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'plasticococococo',
      price: '149934937',
      tel: '6140028922',
      type: 'Fornecedor',
      funcoes: 'produtos',
      status: 'Ativo'
    },
    {
      _id: 4,
      name: 'Vin Disel',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição BBBBBBBBBBBB',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'plasticococococo',
      price: '149934937',
      tel: '6140028922',
      type: 'Fornecedor',
      funcoes: 'controledeacesso',
      status: 'Ativo'
    },
    {
      _id: 5,
      name: 'Drake',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'plasticococococo',
      price: '149934937',
      tel: '6140028922',
      type: 'Fornecedor',
      funcoes: 'notificacoes',
      status: 'Ativo'
    },
    {
      _id: 6,
      name: 'Travis Scots',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'plasticococococo',
      price: '149934937',
      tel: '6140028922',
      type: 'Fornecedor',
      status: 'Inativo',
      funcoes: 'cliente',
    },
    {
      _id: 7,
      name: 'Avril Lavine',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'madeirararara',
      price: '149934937',
      tel: '6140028922',
      type: 'Cliente',
      funcoes: 'cliente',
      status: 'Inativo'
    },
    {
      _id: 8,
      name: 'Ana maria braga',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'madeirararara',
      price: '149934937',
      tel: '6140028922',
      type: 'Cliente',
      funcoes: 'cliente',
      status: 'Inativo'
    },
    {
      _id: 9,
      name: 'Faustão',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'madeirararara',
      price: '149934937',
      tel: '6140028922',
      type: 'Cliente',
      status: 'Inativo',
      funcoes: 'cliente',
    },
    {
      _id: 10,
      name: 'Al abduh jaba mohamed mia khalifa',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'madeirararara',
      price: '149934937',
      tel: '6140028922',
      type: 'Cliente',
      status: 'Inativo',
      funcoes: 'cliente',
    },
    {
      _id: 11,
      name: 'Bolsonaro',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'madeirararara',
      price: '149934937',
      tel: '6140028922',
      type: 'Cliente',
      status: 'Inativo',
      funcoes: 'cliente',
    },
    {
      _id: 12,
      name: 'Putin',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'madeirararara',
      price: '149934937',
      tel: '6140028922',
      type: 'Cliente',
      status: 'Inativo',
      funcoes: 'cliente',
    },
    {
      _id: 13,
      name: 'Donald trump',
      email: 'exemplo@xequemate.com',
      cnpj: '42788247000164',
      permition: 'Permição AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      date: '25122001',
      description: 'A casa é um lar aconchegante e acolhedor, com uma fachada em estilo clássico e bem cuidada. Ao entrar, há uma sala de estar ampla e confortável, decorada com móveis de madeira e estofados macios',
      specification: ' A cozinha é moderna e equipada com todos os utensílios necessários para cozinhar refeições deliciosas. No andar de cima, há três quartos espaçosos, todos com camas confortáveis e decoração agradável',
      doc: [] = [
        '../../../../../assets/images/eee.pdf',
        '../../../../../assets/images/eee.pdf',
      ],
      code: '000000007',
      img: [
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
        '../../../../../assets/images/illustration.jpg',
      ],
      category: 'Material de construção',
      emphasis: false,
      material: 'madeirararara',
      price: '149934937',
      tel: '6140028922',
      type: 'Cliente',
      status: 'Inativo',
      funcoes: 'administrador',
    },

  ];

  getsupplier(): SupplierInterface[] {
    return this.supplier;
  }
}
