export interface SupplierInterface {
    _id: number,
    name: string;
    email: string,
    cnpj: string,
    date: string,
    permition: string,
    material: string,
    price: string,
    namecategory: string,
    category: string,
    tel: string,
    code: string,
    emphasis: boolean,
    img: string[],
    doc: string[],
    specification: string,
    description: string,
    type: string,
    funcoes: string,
    status: string,
    imgcategory: string[],
}
